### PR TITLE
Gamepad rework

### PR DESCRIPTION
**Pull request by berithpy**
It needs some more love/cleanup, looking for feedback, there's an issue for when you disconnect a pad and connect a different pad we should handle that somehow.

### CODE REVIEW

**Comment by berithpy** [comment]
Keymap is no longer needed to create our Gamepad object, i should clear those 1 and 0 from operator and dweller.

**Comment by berithpy** [comment]
Also, the keymap on Gamepad.js is no longer needed, i moved it to a separate file.

**Comment by AlejoAsd** [comment]
Keyboard gamepads aren't being swapped. #18

**Comment by AlejoAsd** [comment]
PS4 controller input is not being detected/processed. #20

**Comment by AlejoAsd** [comment]
I refactored most of the classes in `gamepadConfig` to make it simpler to find keymaps. 

I've also added `justPressed` helper methods to gamepads for controller buttons. Keyboard keys and axes aren't supported yet however. I've set up issues #21 and #22 for this.

I believe we should be splitting keymap buttons into `buttons` and `keys` to make sure there are no issues with overlapping codes (as with `ENTER` and `BUTTON_13`). I'd like some input on this.

**Comment by berithpy** [comment]
Can't control the second player with keyboard only #23

**Comment by berithpy** [comment]
I think this is working _atleast_ as good as it was before changing the gamepad object!

**Comment by AlejoAsd** [comment]
I've included the changes to the new keymap format and added `keyJustPressed` support for gamepad buttons and axes. Both `Dweller` and `Operator` classes are using the corresponding methods to check for input.

I believe the rework is done. If my latest commits are reviewed and approved we can merge this PR.

**Pull request merged**
